# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1psXZ-CGDzi6qVJXTtpKujCRPGNUKOZ0E
"""

print("Pilih part!(1/2) \n Part 1\n Part 2")
pilihan = int(input("Pilihan Part: "))

import os
os.system('cls')

if pilihan == 1:
    n = int(input("Masukkan n: "))
    for i in range(n):
        print(i**2)

elif pilihan == 2:
    n = int(input("Masukkan n: "))
    for i in range(n):
        if i % 2 == 1 or i == 0:
            print(i**2)
else:
    print("Tidak ada\")